name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
      - ci
    paths-ignore:
      - "peer_reminder_flutter/**"
  pull_request:
    branches:
      - master
      - develop
      - ci
    paths-ignore:
      - "peer_reminder_flutter/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn package -B -Dmaven.test.skip --file ./peer_reminder/pom.xml