name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
      - ci
    paths-ignore:
      - "peer_reminder_flutter/**"
  pull_request:
    branches:
      - master
      - develop
      - ci
    paths-ignore:
      - "peer_reminder_flutter/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: peer_reminder

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn package -B -Dmaven.test.skip

    # Ignore error so report can be created later
    - name: Test
      run: mvn test -B --fail-at-end

    # Process and Publish Test Report
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1